#!/bin/bash
set -e

run-suite() {
    echo "Test suite:  $TEST"
    echo ""

    ./tester $TEST
    CODE=$?

    echo ""
    return $CODE
}

cd "${0%/*}"
IFS=$'\n'
FAILURES=false

while read TEST; do
    if ! run-suite "$TEST"; then
        FAILURES=true
    fi
done < <(find . -type f -name \*.test)

if $FAILURES; then
    echo "Failures detected"
    exit 1
fi

echo "Test suites all passed"
