#!/bin/bash
set -e


# Run an entire test suite
#
# Parameters:
#     $1: Test suite / filename
# Returns the same return code as the test suite
run-suite() {
    local CODE

    echo "Test suite:  $1"
    echo ""

    ./tester "$1"
    CODE=$?

    echo ""
    return $CODE
}

cd "${0%/*}"
IFS=$'\n'
FAILURES=false

while read TEST; do
    if ! run-suite "$TEST"; then
        FAILURES=true
    fi
done < <(find . -type f -name \*.test)

if $FAILURES; then
    echo "Failures detected"
    exit 1
fi

echo "Test suites all passed"
